name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Deploy application on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Audit performance website
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://vite-crypto-sample-app.herokuapp.com/
          uploadArtifacts: true
          temporaryPublicStorage: true
